import appen_banner_png from "./imgs/appen-banner.png";
import fire from "./imgs/fire.png";
import fullMoon from "./imgs/full-moon.webp";
import greenmainframe_banner_png from "./imgs/greenmainframe-banner.png";
import launch_ats_banner_png from "./imgs/launch-ats-banner.png";
import ourofino_banner_png from "./imgs/ourofino-banner.png";
import villager_png from "./imgs/villager.png";
import werewolf from "./imgs/werewolf.png";
import winesounds_banner_png from "./imgs/winesounds-banner.png";
import winesounds from "./imgs/winesounds.jpg";

import adventure_map_svg from "./icons/adventure-map.svg";
import angry_soldier_svg from "./icons/angry-soldier.svg";
import api_svg from "./icons/api.svg";
import armor_svg from "./icons/armor.svg";
import aws_ec2_svg from "./icons/aws-ec2.svg";
import boots_svg from "./icons/boots.svg";
import bootstrap_svg from "./icons/bootstrap.svg";
import bow_and_arrow_svg from "./icons/bow-and-arrow.svg";
import coins_svg from "./icons/coins.svg";
import construction_danger_exclamantion_svg from "./icons/construction-danger-exclamantion.svg";
import destructive_magic_svg from "./icons/destructive-magic.svg";
import doors_entrance_svg from "./icons/doors-entrance.svg";
import elf_svg from "./icons/elf.svg";
import fairy_svg from "./icons/fairy.svg";
import front_end_svg from "./icons/frontend.svg";
import helmet_svg from "./icons/helmet.svg";
import item_bag_svg from "./icons/item-bag.svg";
import knight_svg from "./icons/knight.svg";
import orc_svg from "./icons/orc.svg";
import scroll_note_svg from "./icons/scroll-note.svg";
import shield_svg from "./icons/shield.svg";
import sorceress_witch_svg from "./icons/sorceress-witch.svg";
import spell_book_svg from "./icons/spell-book.svg";
import spell_scroll_svg from "./icons/spell-scroll.svg";
import sword_svg from "./icons/sword.svg";
import tavern_indicator_svg from "./icons/tavern-indicator.svg";
import treasure_chest_svg from "./icons/treasure-chest.svg";
import vault_keeper_svg from "./icons/vault-keeper.svg";
import villager_svg from "./icons/villager.svg";
import werewolf_svg from "./icons/werewolf.svg";
import my_cv_pdf from "./pdf/GabrielMaxGB.pdf";

export const FIRE_PNG = fire;
export const FULL_MOON_PNG = fullMoon;
export const VILLAGER_PNG = villager_png;
export const WEREWOLF_PNG = werewolf;
export const WINESOUNDS_JPG = winesounds;
export const APPEN_BANNER_PNG = appen_banner_png;
export const GREENMAINFRAME_BANNER_PNG = greenmainframe_banner_png;
export const LAUNCH_ATS_BANNER_PNG = launch_ats_banner_png;
export const OUROFINO_BANNER_PNG = ourofino_banner_png;
export const WINESOUNDS_BANNER_PNG = winesounds_banner_png;

export const VILLAGER_SVG = villager_svg;
export const WEREWOLF_SVG = werewolf_svg;
export const KNIGHT_SVG = knight_svg;
export const DESTRUCTIVE_MAGIC_SVG = destructive_magic_svg;
export const FRONT_END_SVG = front_end_svg;
export const AWS_EC2_SVG = aws_ec2_svg;
export const BOOTSTRAP_SVG = bootstrap_svg;
export const API_SVG = api_svg;
export const SPELL_SCROLL_SVG = spell_scroll_svg;
export const ADVENTURE_MAP_SVG = adventure_map_svg;
export const SWORD_SVG = sword_svg;
export const ARMOR_SVG = armor_svg;
export const ELF_SVG = elf_svg;
export const ORC_SVG = orc_svg;
export const BOW_AND_ARROW_SVG = bow_and_arrow_svg;
export const ANGRY_SOLDIER_SVG = angry_soldier_svg;
export const ITEM_BAG_SVG = item_bag_svg;
export const FAIRY_SVG = fairy_svg;
export const SPELL_BOOK_SVG = spell_book_svg;
export const HELMET_SVG = helmet_svg;
export const SHIELD_SVG = shield_svg;
export const BOOTS_SVG = boots_svg;
export const SCROLL_NOTE_SVG = scroll_note_svg;
export const VAULT_KEEPER_SVG = vault_keeper_svg;
export const TREASURE_CHEST_SVG = treasure_chest_svg;
export const COINS_SVG = coins_svg;
export const SORCERESS_WITCH_SVG = sorceress_witch_svg;
export const TAVERN_INDICATOR_SVG = tavern_indicator_svg;
export const DOORS_ENTRANCE_SVG = doors_entrance_svg;
export const CONSTRUCTION_DANGER_EXCLAMANTION_SVG =
  construction_danger_exclamantion_svg;

export const MY_CV = my_cv_pdf;
